[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[[redirects]]
  from = "/*"
  to = "/index-static.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[build.processing.images]
  compress = true